spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: ${URL}
        username: ${DATABASE_USER}
        password: ${DATABASE_PASS}
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: false
        properties:
            hibernate:
                format_sql: true
                use_sql_comments: true
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                default_schema: auth
                jdbc:
                    time_zone: UTC
